import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { installDaemonService, uninstallDaemonService } from "../src/daemon-service.js";
import type { LocalStatePaths } from "../src/local-state.js";

const tmpDirs: string[] = [];

afterEach(() => {
  for (const dir of tmpDirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

describe("daemon service integration", () => {
  it("[UC-DAEMON-04-S09] installs a macOS LaunchAgent file for the local daemon", () => {
    const root = createTmpDir();
    const home = createTmpDir();
    const result = installDaemonService({
      paths: paths(root),
      platform: "launchd",
      home,
      entrypoint: "/usr/local/bin/grovie",
    });

    expect(result).toEqual({
      platform: "launchd",
      path: join(home, "Library", "LaunchAgents", "dev.grovie.daemon.plist"),
      action: "installed",
    });
    expect(readFileSync(result.path, "utf8")).toContain("<string>/usr/local/bin/grovie</string>");
    expect(readFileSync(result.path, "utf8")).toContain("Grovie managed daemon service");
    expect(readFileSync(result.path, "utf8")).toContain("<string>daemon</string>");
    expect(readFileSync(result.path, "utf8")).not.toContain("<string>run</string>");
    expect(readFileSync(result.path, "utf8")).toContain(`<string>${root}/daemon/stdout.log</string>`);
  });

  it("[UC-DAEMON-04-S10] installs a Linux systemd user service file for the local daemon", () => {
    const root = createTmpDir();
    const home = createTmpDir();
    const result = installDaemonService({
      paths: paths(root),
      platform: "systemd",
      home,
      entrypoint: "/usr/local/bin/grovie",
    });

    expect(result).toEqual({
      platform: "systemd",
      path: join(home, ".config", "systemd", "user", "grovie.service"),
      action: "installed",
    });
    expect(readFileSync(result.path, "utf8")).toContain("ExecStart=");
    expect(readFileSync(result.path, "utf8")).toContain("Grovie managed daemon service");
    expect(readFileSync(result.path, "utf8")).toContain("/usr/local/bin/grovie daemon");
    expect(readFileSync(result.path, "utf8")).not.toContain("/usr/local/bin/grovie daemon run");
    expect(readFileSync(result.path, "utf8")).toContain(`StandardOutput=append:${root}/daemon/stdout.log`);
  });

  it("[UC-DAEMON-04-S11] uninstalls only the generated user service file", () => {
    const root = createTmpDir();
    const home = createTmpDir();
    const installed = installDaemonService({
      paths: paths(root),
      platform: "systemd",
      home,
      entrypoint: "/usr/local/bin/grovie",
    });

    expect(existsSync(installed.path)).toBe(true);

    const result = uninstallDaemonService({
      paths: paths(root),
      platform: "systemd",
      home,
    });

    expect(result).toEqual({
      platform: "systemd",
      path: installed.path,
      action: "uninstalled",
    });
    expect(existsSync(installed.path)).toBe(false);
  });

  it("[UC-DAEMON-04-S11] refuses to overwrite or remove service files not generated by Grovie", () => {
    const root = createTmpDir();
    const home = createTmpDir();
    const servicePath = join(home, ".config", "systemd", "user", "grovie.service");
    writeFileSync(servicePath, "[Service]\nExecStart=/usr/bin/other\n", "utf8");

    expect(() =>
      installDaemonService({
        paths: paths(root),
        platform: "systemd",
        home,
        entrypoint: "/usr/local/bin/grovie",
      }),
    ).toThrow("Refusing to overwrite existing service file because it was not generated by Grovie");
    expect(() =>
      uninstallDaemonService({
        paths: paths(root),
        platform: "systemd",
        home,
      }),
    ).toThrow("Refusing to remove existing service file because it was not generated by Grovie");
    expect(readFileSync(servicePath, "utf8")).toContain("/usr/bin/other");
  });
});

function createTmpDir(): string {
  const dir = mkdtempSync(join(tmpdir(), "grovie-daemon-service-"));
  tmpDirs.push(dir);
  mkdirSync(join(dir, ".config", "systemd", "user"), { recursive: true });
  mkdirSync(join(dir, "Library", "LaunchAgents"), { recursive: true });
  return dir;
}

function paths(root: string): LocalStatePaths {
  return {
    root,
    reposDir: join(root, "repos"),
    worktreesDir: join(root, "worktrees"),
    runsDir: join(root, "runs"),
    locksDir: join(root, "locks"),
    sessionsDir: join(root, "sessions"),
  };
}
