import { join } from "node:path";
import type { GrovieConfig } from "../config.js";
import type { GitHubIssue, GitHubRelatedPullRequest } from "../github.js";
import { buildBranchName, buildRunId, buildRunTimestamp, buildSessionId, LocalState, type PreparedRun } from "../local-state.js";
import { createRuntime, type RuntimeName } from "../runtime.js";
import { renderCliRunOutput, renderRunResultComment, upsertRunProgressComment } from "./comments.js";
import { buildTaskContext, resolveTriggerContext } from "./context.js";
import { resolveSummaryMachineId, toErrorMessage } from "./helpers.js";
import type { PreparedIssueRun, RunIssueInput, RunLocalState, RunSummary } from "./types.js";

export function prepareIssueRun(input: RunIssueInput): PreparedIssueRun {
  const repository = `${input.issueReference.owner}/${input.issueReference.repo}`;

  if (repository !== input.repository) {
    return {
      ok: false,
      result: {
        exitCode: 1,
        stderr: `Issue repository ${repository} does not match runner repository ${input.repository}.`,
      },
    };
  }

  const issueResult = input.github.readIssue(input.issueReference);

  if (!issueResult.ok) {
    return {
      ok: false,
      result: {
        exitCode: 1,
        stderr: issueResult.error.message,
      },
    };
  }

  const issue = issueResult.value;
  const relatedPullRequestsResult = input.github.readRelatedPullRequests?.(input.issueReference) ?? {
    ok: true as const,
    value: [],
  };

  if (!relatedPullRequestsResult.ok) {
    return {
      ok: false,
      result: {
        exitCode: 1,
        stderr: relatedPullRequestsResult.error.message,
      },
    };
  }

  const localState = input.localState ?? new LocalState();
  const runtime = input.runtime ?? createRuntime(input.agent);
  const now = new Date();
  const agentId = input.agentId ?? input.agent;
  const triggerContext = resolveTriggerContext({
    input,
    localState,
    agentId,
    issue,
    relatedPullRequests: relatedPullRequestsResult.value,
    repository,
  });
  const machineId = resolveSummaryMachineId(agentId);
  const sessionId = buildSessionId(repository, input.issueReference.number, agentId);
  const task = buildTaskContext({
    issue,
    relatedPullRequests: relatedPullRequestsResult.value,
    configPath: input.configPath,
    runtime: runtime.name,
    agentInstructions: input.agentInstructions,
    runRequest: input.runRequest,
    triggerContext,
  });

  let run: PreparedRun;

  try {
    run = localState.prepareRun({
      repository,
      issueNumber: input.issueReference.number,
      agentId,
      defaultBranch: issue.defaultBranch,
      branchPrefix: input.config.branches.prefix,
      now,
      prompt: "Prompt will be generated by the selected runtime.",
      task,
      runRequest: input.runRequest,
    });
  } catch (error) {
    const summary = fallbackRunSummary({
      issue,
      config: input.config,
      localState,
      sessionId,
      runId: buildRunId(sessionId, buildRunTimestamp(now)),
      agentId,
      machineId,
      runtime: runtime.name,
      error: toErrorMessage(error),
      errorSource: "prepare",
    });
    const commentResult = input.github.createIssueComment(input.issueReference, renderRunResultComment(summary));

    if (!commentResult.ok) {
      return {
        ok: false,
        result: {
          exitCode: 1,
          stderr: `${summary.error}\nFailed to post result comment: ${commentResult.error.message}`,
        },
      };
    }

    return {
      ok: false,
      result: {
        exitCode: 1,
        stdout: renderCliRunOutput({ ...summary, comment: commentResult.value }),
        stderr: summary.error,
      },
    };
  }

  localState.appendEvent(run, "run.started", {
    runtime: runtime.name,
  });

  const progressComment = upsertRunProgressComment({
    issue,
    issueReference: input.issueReference,
    github: input.github,
    run,
    runtime: runtime.name,
    agentId,
    machineId,
    startedAt: now.toISOString(),
  });

  if (!progressComment.ok) {
    localState.appendEvent(run, "progress_comment.failed", {
      message: progressComment.error,
    });
  } else {
    localState.appendEvent(run, progressComment.action === "updated" ? "progress_comment.updated" : "progress_comment.created", {
      id: progressComment.comment.id,
      url: progressComment.comment.url,
    });
  }

  return {
    ok: true,
    issue,
    run,
    localState,
    runtime,
    lifecycleComment: progressComment.ok
      ? {
        id: progressComment.comment.id,
        url: progressComment.comment.url,
      }
      : undefined,
  };
}

function fallbackRunSummary(input: {
  issue: GitHubIssue;
  config: GrovieConfig;
  localState: RunLocalState;
  sessionId: string;
  runId: string;
  agentId: string;
  machineId: string;
  runtime: RuntimeName;
  error: string;
  errorSource: "prepare";
}): RunSummary {
  return {
    status: "failed",
    issue: input.issue,
    runId: input.runId,
    branchName: buildBranchName(input.config.branches.prefix, input.sessionId),
    runDir: join(input.localState.getPaths().runsDir, input.runId),
    runtime: input.runtime,
    agentId: input.agentId,
    machineId: input.machineId,
    error: input.error,
    errorSource: input.errorSource,
  };
}
