import { join } from "node:path";
import type { GrovieConfig } from "./config.js";
import {
  formatIssueReference,
  type CreatedComment,
  type GitHubGateway,
  type GitHubIssue,
  type IssueReference,
} from "./github.js";
import { buildBranchName, buildRunId, LocalState, type LocalStatePaths, type PreparedRun } from "./local-state.js";
import { GitResultHandler, type HandleRunResultResult, type ResultHandler } from "./result.js";
import { CodexRuntime, type AgentRuntime, type RuntimeMonitor, type RuntimeRunResult } from "./runtime.js";

export type RunIssueInput = {
  issueReference: IssueReference;
  config: GrovieConfig;
  configPath: string;
  agent: "codex";
  github: GitHubGateway;
  runtime?: AgentRuntime;
  localState?: RunLocalState;
  resultHandler?: ResultHandler;
};

export type RunIssueResult = {
  exitCode: number;
  stdout?: string;
  stderr?: string;
  canceled?: boolean;
};

export type RunIssueAsyncInput = RunIssueInput & {
  monitor?: RuntimeMonitor;
};

export type RunLocalState = {
  getPaths(): LocalStatePaths;
  prepareRun(input: {
    repository: string;
    issueNumber: number;
    defaultBranch: string;
    branchPrefix: string;
    prompt: string;
    task: Record<string, unknown>;
  }): PreparedRun;
  appendEvent(run: PreparedRun, type: string, data?: Record<string, unknown>): void;
};

type RunSummary = {
  status: "success" | "failure" | "canceled";
  issue: GitHubIssue;
  runId: string;
  branchName: string;
  runDir: string;
  runtime: "codex";
  result?: HandleRunResultResult;
  comment?: CreatedComment;
  error?: string;
};

export function runIssue(input: RunIssueInput): RunIssueResult {
  const prepared = prepareIssueRun(input);

  if (!prepared.ok) {
    return prepared.result;
  }

  return finishRun({
    ...prepared,
    issueReference: input.issueReference,
    github: input.github,
    agent: input.agent,
    config: input.config,
    configPath: input.configPath,
    resultHandler: input.resultHandler,
    runtimeResult: prepared.runtime.run({
      run: prepared.run,
      issue: prepared.issue,
    }),
  });
}

export async function runIssueAsync(input: RunIssueAsyncInput): Promise<RunIssueResult> {
  const prepared = prepareIssueRun(input);

  if (!prepared.ok) {
    return prepared.result;
  }

  const runtimeResult =
    prepared.runtime.runAsync === undefined
      ? prepared.runtime.run({
        run: prepared.run,
        issue: prepared.issue,
        monitor: input.monitor,
      })
      : await prepared.runtime.runAsync({
        run: prepared.run,
        issue: prepared.issue,
        monitor: input.monitor,
      });

  return finishRun({
    ...prepared,
    issueReference: input.issueReference,
    github: input.github,
    agent: input.agent,
    config: input.config,
    configPath: input.configPath,
    resultHandler: input.resultHandler,
    runtimeResult,
  });
}

type PreparedIssueRun =
  | {
    ok: true;
    issue: GitHubIssue;
    run: PreparedRun;
    localState: RunLocalState;
    runtime: AgentRuntime;
  }
  | {
    ok: false;
    result: RunIssueResult;
  };

function prepareIssueRun(input: RunIssueInput): PreparedIssueRun {
  const repository = `${input.issueReference.owner}/${input.issueReference.repo}`;

  if (!input.config.repositories.allowed.includes(repository)) {
    return {
      ok: false,
      result: {
        exitCode: 1,
        stderr: `Repository ${repository} is not allowed by ${input.configPath}.`,
      },
    };
  }

  const issueResult = input.github.readIssue(input.issueReference);

  if (!issueResult.ok) {
    return {
      ok: false,
      result: {
        exitCode: 1,
        stderr: issueResult.error.message,
      },
    };
  }

  const issue = issueResult.value;
  const localState = input.localState ?? new LocalState();
  const runtime = input.runtime ?? new CodexRuntime();
  const task = buildTaskContext({
    issue,
    configPath: input.configPath,
    agent: input.agent,
  });

  let run: PreparedRun;

  try {
    run = localState.prepareRun({
      repository,
      issueNumber: input.issueReference.number,
      defaultBranch: issue.defaultBranch,
      branchPrefix: input.config.branches.prefix,
      prompt: "Prompt will be generated by the selected runtime.",
      task,
    });
  } catch (error) {
    const summary = fallbackRunSummary({
      issue,
      config: input.config,
      localState,
      error: toErrorMessage(error),
    });
    const commentResult = input.github.createIssueComment(input.issueReference, renderRunComment(summary));

    if (!commentResult.ok) {
      return {
        ok: false,
        result: {
          exitCode: 1,
          stderr: `${summary.error}\nFailed to post result comment: ${commentResult.error.message}`,
        },
      };
    }

    return {
      ok: false,
      result: {
        exitCode: 1,
        stdout: renderCliRunOutput({ ...summary, comment: commentResult.value }),
        stderr: summary.error,
      },
    };
  }

  localState.appendEvent(run, "run.started", {
    runtime: input.agent,
  });

  return {
    ok: true,
    issue,
    run,
    localState,
    runtime,
  };
}

function finishRun(input: {
  issue: GitHubIssue;
  run: PreparedRun;
  localState: RunLocalState;
  issueReference: IssueReference;
  github: GitHubGateway;
  agent: "codex";
  config: GrovieConfig;
  configPath: string;
  resultHandler?: ResultHandler;
  runtimeResult: RuntimeRunResult;
}): RunIssueResult {
  let result: HandleRunResultResult | undefined;
  let resultError: string | undefined;

  if (input.runtimeResult.ok) {
    const handler = input.resultHandler ?? new GitResultHandler(input.github);

    try {
      result = handler.handle({
        run: input.run,
        issue: input.issue,
        config: input.config,
        configPath: input.configPath,
        repository: `${input.issue.reference.owner}/${input.issue.reference.repo}`,
        runtime: input.agent,
        execution: input.runtimeResult.execution,
      });
      input.localState.appendEvent(input.run, "result.handled", {
        kind: result.kind,
      });
    } catch (error) {
      resultError = toErrorMessage(error);
      input.localState.appendEvent(input.run, "result.failed", {
        message: resultError,
      });
    }
  }

  const summary = runSummaryFromRuntimeResult({
    issue: input.issue,
    run: input.run,
    runtimeResult: input.runtimeResult,
    result,
    resultError,
  });

  input.localState.appendEvent(input.run, runEventType(input.runtimeResult), {
    runtime: input.agent,
    exitCode: input.runtimeResult.execution.exitCode,
  });

  const commentResult = input.github.createIssueComment(input.issueReference, renderRunComment(summary));

  if (!commentResult.ok) {
    input.localState.appendEvent(input.run, "comment.failed", {
      message: commentResult.error.message,
    });

    return {
      exitCode: 1,
      stdout: renderCliRunOutput(summary),
      stderr: `Failed to post result comment: ${commentResult.error.message}`,
      canceled: summary.status === "canceled" ? true : undefined,
    };
  }

  input.localState.appendEvent(input.run, "comment.created", {
    id: commentResult.value.id,
    url: commentResult.value.url,
  });

  return {
    exitCode: summary.status === "failure" ? 1 : 0,
    stdout: renderCliRunOutput({ ...summary, comment: commentResult.value }),
    stderr: summary.error,
    canceled: summary.status === "canceled" ? true : undefined,
  };
}

function buildTaskContext(input: { issue: GitHubIssue; configPath: string; agent: "codex" }): Record<string, unknown> {
  return {
    schemaVersion: 1,
    source: "grovie run",
    configPath: input.configPath,
    runtime: input.agent,
    repository: `${input.issue.reference.owner}/${input.issue.reference.repo}`,
    issue: {
      number: input.issue.reference.number,
      title: input.issue.title,
      state: input.issue.state,
      labels: input.issue.labels,
      defaultBranch: input.issue.defaultBranch,
      body: input.issue.body,
      comments: input.issue.comments,
    },
  };
}

function fallbackRunSummary(input: {
  issue: GitHubIssue;
  config: GrovieConfig;
  localState: RunLocalState;
  error: string;
}): RunSummary {
  const repository = `${input.issue.reference.owner}/${input.issue.reference.repo}`;
  const runId = buildRunId(repository, input.issue.reference.number);

  return {
    status: "failure",
    issue: input.issue,
    runId,
    branchName: buildBranchName(input.config.branches.prefix, input.issue.reference.number),
    runDir: join(input.localState.getPaths().runsDir, runId),
    runtime: "codex",
    error: input.error,
  };
}

function runSummaryFromRuntimeResult(input: {
  issue: GitHubIssue;
  run: PreparedRun;
  runtimeResult: RuntimeRunResult;
  result?: HandleRunResultResult;
  resultError?: string;
}): RunSummary {
  const status = input.runtimeResult.ok
    ? input.resultError === undefined
      ? "success"
      : "failure"
    : input.runtimeResult.canceled === true
      ? "canceled"
      : "failure";

  return {
    status,
    issue: input.issue,
    runId: input.run.runId,
    branchName: input.run.branchName,
    runDir: input.run.runDir,
    runtime: input.runtimeResult.execution.runtime,
    result: input.result,
    error: input.resultError ?? (input.runtimeResult.ok ? undefined : input.runtimeResult.error.message),
  };
}

function renderRunComment(summary: RunSummary): string {
  const lines = [
    `Grovie run ${runStatusVerb(summary.status)}.`,
    "",
    `- Result: ${summary.status}`,
    `- Runtime: ${summary.runtime}`,
    `- Issue: ${formatIssueReference(summary.issue.reference)}`,
    `- Branch: \`${summary.branchName}\` (local; not pushed)`,
    `- Run id: \`${summary.runId}\``,
    `- Run directory: \`${summary.runDir}\``,
  ];

  if (summary.error !== undefined) {
    lines.push(`- Error: ${summarizeError(summary.error)}`);
  }

  if (summary.result?.kind === "no-changes") {
    lines.push("- Changes: none");
  }

  if (summary.result?.kind === "pull-request") {
    lines.push(`- Pull request: ${summary.result.pullRequest.url}`);
  }

  return lines.join("\n");
}

function runEventType(runtimeResult: RuntimeRunResult): "run.succeeded" | "run.failed" | "run.canceled" {
  if (runtimeResult.ok) {
    return "run.succeeded";
  }

  return runtimeResult.canceled === true ? "run.canceled" : "run.failed";
}

function runStatusVerb(status: RunSummary["status"]): string {
  if (status === "success") {
    return "completed";
  }

  if (status === "failure") {
    return "failed";
  }

  return status;
}

function renderCliRunOutput(summary: RunSummary): string {
  const lines = [
    "grovie run",
    "",
    `Result: ${summary.status}`,
    `Issue: ${formatIssueReference(summary.issue.reference)}`,
    `Branch: ${summary.branchName}`,
    `Run id: ${summary.runId}`,
    `Run directory: ${summary.runDir}`,
  ];

  if (summary.comment !== undefined) {
    lines.push(`Comment: ${summary.comment.url}`);
  }

  if (summary.result?.kind === "no-changes") {
    lines.push("Changes: none");
  }

  if (summary.result?.kind === "pull-request") {
    lines.push(`Pull request: ${summary.result.pullRequest.url}`);
  }

  return lines.join("\n");
}

function toErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function summarizeError(error: string): string {
  const singleLine = error.replace(/\s+/g, " ").trim();
  return singleLine.length > 300 ? `${singleLine.slice(0, 297)}...` : singleLine;
}
