import { join } from "node:path";
import type { GrovieConfig } from "./config.js";
import {
  formatIssueReference,
  type CreatedComment,
  type GitHubGateway,
  type GitHubIssue,
  type IssueReference,
} from "./github.js";
import { buildBranchName, buildRunId, LocalState, type LocalStatePaths, type PreparedRun } from "./local-state.js";
import { CodexRuntime, type AgentRuntime, type RuntimeRunResult } from "./runtime.js";

export type RunIssueInput = {
  issueReference: IssueReference;
  config: GrovieConfig;
  configPath: string;
  agent: "codex";
  github: GitHubGateway;
  runtime?: AgentRuntime;
  localState?: RunLocalState;
};

export type RunIssueResult = {
  exitCode: number;
  stdout?: string;
  stderr?: string;
};

export type RunLocalState = {
  getPaths(): LocalStatePaths;
  prepareRun(input: {
    repository: string;
    issueNumber: number;
    defaultBranch: string;
    branchPrefix: string;
    prompt: string;
    task: Record<string, unknown>;
  }): PreparedRun;
  appendEvent(run: PreparedRun, type: string, data?: Record<string, unknown>): void;
};

type RunSummary = {
  status: "success" | "failure";
  issue: GitHubIssue;
  runId: string;
  branchName: string;
  runDir: string;
  runtime: "codex";
  comment?: CreatedComment;
  error?: string;
};

export function runIssue(input: RunIssueInput): RunIssueResult {
  const repository = `${input.issueReference.owner}/${input.issueReference.repo}`;

  if (!input.config.repositories.allowed.includes(repository)) {
    return {
      exitCode: 1,
      stderr: `Repository ${repository} is not allowed by ${input.configPath}.`,
    };
  }

  const issueResult = input.github.readIssue(input.issueReference);

  if (!issueResult.ok) {
    return {
      exitCode: 1,
      stderr: issueResult.error.message,
    };
  }

  const issue = issueResult.value;
  const localState = input.localState ?? new LocalState();
  const runtime = input.runtime ?? new CodexRuntime();
  const task = buildTaskContext({
    issue,
    configPath: input.configPath,
    agent: input.agent,
  });

  let run: PreparedRun;

  try {
    run = localState.prepareRun({
      repository,
      issueNumber: input.issueReference.number,
      defaultBranch: issue.defaultBranch,
      branchPrefix: input.config.branches.prefix,
      prompt: "Prompt will be generated by the selected runtime.",
      task,
    });
  } catch (error) {
    const summary = fallbackRunSummary({
      issue,
      config: input.config,
      localState,
      error: toErrorMessage(error),
    });
    const commentResult = input.github.createIssueComment(input.issueReference, renderRunComment(summary));

    if (!commentResult.ok) {
      return {
        exitCode: 1,
        stderr: `${summary.error}\nFailed to post result comment: ${commentResult.error.message}`,
      };
    }

    return {
      exitCode: 1,
      stdout: renderCliRunOutput({ ...summary, comment: commentResult.value }),
      stderr: summary.error,
    };
  }

  localState.appendEvent(run, "run.started", {
    runtime: input.agent,
  });

  const runtimeResult = runtime.run({
    run,
    issue,
  });
  const summary = runSummaryFromRuntimeResult({
    issue,
    run,
    runtimeResult,
  });

  localState.appendEvent(run, runtimeResult.ok ? "run.succeeded" : "run.failed", {
    runtime: input.agent,
    exitCode: runtimeResult.execution.exitCode,
  });

  const commentResult = input.github.createIssueComment(input.issueReference, renderRunComment(summary));

  if (!commentResult.ok) {
    localState.appendEvent(run, "comment.failed", {
      message: commentResult.error.message,
    });

    return {
      exitCode: 1,
      stdout: renderCliRunOutput(summary),
      stderr: `Failed to post result comment: ${commentResult.error.message}`,
    };
  }

  localState.appendEvent(run, "comment.created", {
    id: commentResult.value.id,
    url: commentResult.value.url,
  });

  return {
    exitCode: summary.status === "success" ? 0 : 1,
    stdout: renderCliRunOutput({ ...summary, comment: commentResult.value }),
    stderr: summary.error,
  };
}

function buildTaskContext(input: { issue: GitHubIssue; configPath: string; agent: "codex" }): Record<string, unknown> {
  return {
    schemaVersion: 1,
    source: "grovie run",
    configPath: input.configPath,
    runtime: input.agent,
    repository: `${input.issue.reference.owner}/${input.issue.reference.repo}`,
    issue: {
      number: input.issue.reference.number,
      title: input.issue.title,
      state: input.issue.state,
      labels: input.issue.labels,
      defaultBranch: input.issue.defaultBranch,
      body: input.issue.body,
      comments: input.issue.comments,
    },
  };
}

function fallbackRunSummary(input: {
  issue: GitHubIssue;
  config: GrovieConfig;
  localState: RunLocalState;
  error: string;
}): RunSummary {
  const repository = `${input.issue.reference.owner}/${input.issue.reference.repo}`;
  const runId = buildRunId(repository, input.issue.reference.number);

  return {
    status: "failure",
    issue: input.issue,
    runId,
    branchName: buildBranchName(input.config.branches.prefix, input.issue.reference.number),
    runDir: join(input.localState.getPaths().runsDir, runId),
    runtime: "codex",
    error: input.error,
  };
}

function runSummaryFromRuntimeResult(input: {
  issue: GitHubIssue;
  run: PreparedRun;
  runtimeResult: RuntimeRunResult;
}): RunSummary {
  return {
    status: input.runtimeResult.ok ? "success" : "failure",
    issue: input.issue,
    runId: input.run.runId,
    branchName: input.run.branchName,
    runDir: input.run.runDir,
    runtime: input.runtimeResult.execution.runtime,
    error: input.runtimeResult.ok ? undefined : input.runtimeResult.error.message,
  };
}

function renderRunComment(summary: RunSummary): string {
  const lines = [
    `Grovie run ${summary.status === "success" ? "completed" : "failed"}.`,
    "",
    `- Result: ${summary.status}`,
    `- Runtime: ${summary.runtime}`,
    `- Issue: ${formatIssueReference(summary.issue.reference)}`,
    `- Branch: \`${summary.branchName}\` (local; not pushed)`,
    `- Run id: \`${summary.runId}\``,
    `- Run directory: \`${summary.runDir}\``,
  ];

  if (summary.error !== undefined) {
    lines.push(`- Error: ${summarizeError(summary.error)}`);
  }

  return lines.join("\n");
}

function renderCliRunOutput(summary: RunSummary): string {
  const lines = [
    "grovie run",
    "",
    `Result: ${summary.status}`,
    `Issue: ${formatIssueReference(summary.issue.reference)}`,
    `Branch: ${summary.branchName}`,
    `Run id: ${summary.runId}`,
    `Run directory: ${summary.runDir}`,
  ];

  if (summary.comment !== undefined) {
    lines.push(`Comment: ${summary.comment.url}`);
  }

  return lines.join("\n");
}

function toErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function summarizeError(error: string): string {
  const singleLine = error.replace(/\s+/g, " ").trim();
  return singleLine.length > 300 ? `${singleLine.slice(0, 297)}...` : singleLine;
}
